/************
 		The table: table_io_waits_summary_by_table
 		Link: https://dev.mysql.com/doc/mysql-perfschema-excerpt/8.0/en/performance-schema-table-io-waits-summary-by-table-table.html
 		Desc:  The table_io_waits_summary_by_table table aggregates all table I/O wait events, as generated by the wait/io/table/sql/handler instrument. The grouping is by table.
    	The table_io_waits_summary_by_table table has these grouping columns to indicate how the table aggregates events: OBJECT_TYPE, OBJECT_SCHEMA, and OBJECT_NAME. These columns have the same meaning as in the events_waits_current table. They identify the table to which the row applies.
*****************/

SELECT object_schema, 
	object_name, 
  count_star, -- A summry of both COUNT_READ and COUNT_WRITE
  count_read, 
  count_insert, 
  count_update, 
  count_delete, 
  sum_timer_read,
  sum_timer_write, 
  sum_timer_insert, 
  sum_timer_update, 
  sum_timer_delete
FROM performance_schema.table_io_waits_summary_by_table  
WHERE object_type = 'TABLE'
	-- AND object_name = 'actor' 
    -- AND object_schema = 'sakila';